#!/usr/bin/env bash
# Sync the canonical D1 sync Worker from the apple-sync-kit repo into this skill.
#
# The Worker source lives canonically in `apple-sync-kit/worker/`. This skill
# ships a snapshot of it so a note-only user can deploy without cloning the
# kit repo. Re-run this script whenever the canonical Worker is updated.
#
# The skill-specific files are NEVER overwritten:
#   - wrangler.toml      (database_id, ENTITIES, migrations_dir)
#   - sync-from-kit.sh   (this script itself)
# Only the canonical source (src/, migrations/, package.json, tests, ...) is synced.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEST="$SCRIPT_DIR"

# Prefer a local sibling checkout (fast, offline, reflects uncommitted work).
# Walk up the tree looking for a sibling `apple-sync-kit/worker` so the script
# works regardless of how deep this skill sits under the workspace root.
KIT_DIR=""
dir="$SCRIPT_DIR"
while [[ "$dir" != "/" ]]; do
  candidate="$dir/apple-sync-kit/worker"
  if [[ -f "$candidate/src/index.ts" ]]; then
    KIT_DIR="$candidate"
    break
  fi
  dir="$(dirname "$dir")"
done

# No local checkout: shallow-clone the canonical repo to a temp dir.
TMP_DIR=""
if [[ -z "$KIT_DIR" ]]; then
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT
  echo "No local apple-sync-kit found; cloning from origin into $TMP_DIR ..."
  git clone --depth 1 https://github.com/FradSer/apple-sync-kit.git "$TMP_DIR/kit"
  KIT_DIR="$TMP_DIR/kit/worker"
fi

if [[ ! -f "$KIT_DIR/src/index.ts" ]]; then
  echo "error: canonical Worker not found at $KIT_DIR/src/index.ts" >&2
  exit 1
fi

echo "Syncing canonical Worker from: $KIT_DIR"
echo "            into this skill at: $DEST"

# rsync the canonical tree, preserving skill-specific files and local artifacts.
#   - wrangler.toml        consumer-specific config (database_id, ENTITIES)
#   - wrangler.toml.example consumer-specific example (default entities differ)
#   - sync-from-kit.sh     this script
#   - .gitignore           consumer keeps its own (ignores the real wrangler.toml)
#   - node_modules/.wrangler  local build state
#   - pnpm-lock.yaml       regenerated by `pnpm install`; may differ per consumer
rsync -a --delete \
  --exclude 'wrangler.toml' \
  --exclude 'wrangler.toml.example' \
  --exclude 'sync-from-kit.sh' \
  --exclude '.gitignore' \
  --exclude 'node_modules' \
  --exclude '.wrangler' \
  --exclude 'pnpm-lock.yaml' \
  "$KIT_DIR/" "$DEST/"

# The canonical test suite targets the kit repo's dual-use wrangler.toml (all
# five entities) and does not pass against a narrower consumer config. Drop it
# here; run tests in the kit repo instead.
rm -rf "$DEST/test"

echo "Done. Review with: git status"
echo "Next: pnpm install && pnpm exec wrangler deploy"
